# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'donAIte' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for donAIte
 pod 'SnapKit', '~> 5.0.0'
 pod 'RxSwift', '6.1.0'
 pod 'Kingfisher'
 pod 'RxCocoa', '6.1.0'
 pod 'NKButton'


end
